version: '3.5'
services:
  nginx:
    container_name: nginx
    restart: always
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./.docker/mysql/:/var/lib/mysql
    networks:
      - app_network

  adminer:
    container_name: adminer
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080
    depends_on:
      - mysql
    networks:
      - app_network

networks:
  app_network:
    name: app_network
